### ISSUE TITLE
Managing Bundles or Packages based on users access

### ISSUE THREAD

**Issue by hiddenpearls** [easydigitaldownloads/library#103]
I am setting up EDD for selling a Pro version with add-ons as a bundle i.e A Package.
when user purchases, they will only get a download file for Pro not for add-ons.
So, when they activate the license, then they can Install the add-ons from plugin settings page.
I want to setup these add-ons in EDD along with Pro as a Download. So automatic updates could work for these add-ons as well.
How will One license key work for all these Products i.e Pro and add-ons?

**Comment by pippinsplugins** [comment]
Hi!

Please go ahead and open a support ticket through our support portal: https://easydigitaldownloads.com/support

we use GitHub for development tracking only.
