### ISSUE TITLE
Adjust commissions cart item price if fees applied to order

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/library#107]
As per the new filter (`eddc_calc_commission_amount_args`) added in Commissions 3.4.4, I have written a code snippet that adjusts the cart item price to take into account any "fees" applied to the order, such as from extensions **Discounts Pro** and **Points & Rewards**.

The way fees currently work, mean the store takes the full hit and the commission recipient still receives 50% of the cart item price. Using this sample, the fees are deducted from the cart item price meaning the correct amount is allocated to the vendor.

Will submit PR to go along with this issue.

**Comment by mintplugins** [comment]
Hey David,

Just to confirm, have you played with the "Calculation Base" setting in EDD Commissions? I believe it _should_ do this already. 

<img width="1199" alt="screen shot 2017-12-01 at 3 24 47 pm" src="https://user-images.githubusercontent.com/1638128/33501791-de081df4-d6ab-11e7-84b4-8121ad4366d2.png">

**Comment by davidsherlock** [comment]
@mintplugins, thanks for the heads up but that setting is useless if you need to account for taxes using the other options. That's the reason I wrote this example to help with this situation.

**Comment by davidsherlock** [comment]
My apologies, i mean the other way around (using item subtotal - I have a rare use case here on my store). It does account for taxes/fees at the minute.

**Comment by davidsherlock** [comment]
@mintplugins, can you close this issue off please? My use case is too specific for a code snippet. I wanted to account for points & rewards and discount pro discounts when subtotal was used, but not other discount types. Not a good enough example for the library though, too specific 👍
