### ISSUE TITLE
All Access - only count last download

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/library#112]
A store is selling video files. To prevent download timeouts, it's broken the videos into multiple files and attached each chunk to the product as separate files. Because of this, the store only wants the last file attached to each product to count against the download limit. A filter hook is being added to make this possible here: https://github.com/easydigitaldownloads/edd-all-access/issues/178

In this issue I'll add a function which hooks to that to accomplish that.

**Comment by mintplugins** [comment]
Sending this to the customer to test here:
https://secure.helpscout.net/conversation/485552774/72362?folderId=749231

**Comment by pippinsplugins** [comment]
PR looks good.
