### ISSUE TITLE
Feature Request: EDD purchase RCP Subscription

### ISSUE THREAD

**Issue by Mono-Code** [easydigitaldownloads/library#118]
I wasn't able to find anything in the custom snippets or in the addons for this feature. I was wondering if it would be possible to allow Easy Digital Downloads to allow an individual to purchase an RCP subscription (in case they are interested in both a subscription & product(s)).

**Comment by mindctrl** [comment]
@Mono-Code here's the closest thing we have at the moment:  https://raw.githubusercontent.com/restrictcontentpro/library/master/integrations/easy-digital-downloads/rcp-purchase-via-edd.php
