### ISSUE TITLE
Recurring one subscription fatal error

### ISSUE THREAD

**Issue by misulicus** [easydigitaldownloads/library#129]
Added the snippet to the functions.php file and checkout breaks,
````
[10-Nov-2018 12:24:28 UTC] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function pw_edd_recurring_limit_one_subscription(), 1 passed in D:\MAMP\htdocs\edd\wp-includes\class-wp-hook.php on line 288 and exactly 2 expected in D:\MAMP\htdocs\edd\wp-content\themes\themedd\functions.php:71
````

i change the add_action and added the params at the end and it seems to work now
`add_action( 'edd_checkout_error_checks', 'pw_edd_recurring_limit_one_subscription', 10, 2 );`

Also there seems to be throwing lots of deprecated notices

**Comment by misulicus** [comment]
The snippet below is edited to fix the fatal error and the notices and it seems to work correctly. Not sure how we "update" the code here so i'm leaving it here:

````
function pw_edd_recurring_limit_one_subscription( $valid_data, $post_data ) {
	
	if( ! class_exists( 'EDD_Recurring_Customer' ) ) {
		return;
	}

	if( ! is_user_logged_in() ) {
		return;
	}

	$purchase_data = array(
		'downloads' => edd_get_cart_contents()
	);

	$subscriber = new EDD_Recurring_Subscriber( get_current_user_id(), true );
	$existing = $subscriber->has_active_subscription();
	
	if( $existing && EDD_Recurring()->is_purchase_recurring( $purchase_data ) ) {
		edd_set_error( 'edd-one-subscription', __( 'You already have an active subscription so may not purchase a second one.', 'edd' ) );
	}

}
add_action( 'edd_checkout_error_checks', 'pw_edd_recurring_limit_one_subscription', 10, 2 );
````

**Comment by pippinsplugins** [comment]
@misulicus you can update the code here by editing the relevant .html file: https://github.com/easydigitaldownloads/library/blob/master/_extensions/recurring-payments/one-subscription.html

**Comment by pippinsplugins** [comment]
PR: https://github.com/easydigitaldownloads/library/pull/130
