### ISSUE TITLE
New FES Snippet for Content-Restricting Vendor data 

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/library#77]
This will allow Vendors to submit data - like an embedded video - and have it be automatically output into the Product's description wrapped in [edd_restrict] shortcodes. The content will only display for customers who have purchased the product.

**Comment by mintplugins** [comment]
PR: https://github.com/easydigitaldownloads/library/pull/78

**Comment by pippinsplugins** [comment]
Nice.
