### ISSUE TITLE
[Snippet Request] Safe way to check if a customer has access to a download

### ISSUE THREAD

**Issue by rubengc** [easydigitaldownloads/library#88]
EDD core has the function edd_user_has_purchased() to check if current user has already purchased a download

But there is more checks to see If the site has EDD SL and If user has limit the download and probably there are other conditionals to check based in other plugins

So, how can I check if user has purchased, has an active license and do not have exceed the limit of download times?

I was thinking about this and i do not know If EDD core should include a method (with filters) to check the completely aviability of a download for a customer or this question can be solved adding a note for developers about how to check this aviability

**Comment by brashrebel** [comment]
@rubengc thanks for the request and sorry about the lack of acknowledgement. Curious, [this filter](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/process-download.php#L65) is built into the file download process. Is that what you're looking for?

**Comment by rubengc** [comment]
Hi @brashrebel 

Don't worry, actually the plugin that I was looking this feature has been acquired by another company so I don't need to perform this check

Thank you so much for reply
