### ISSUE TITLE
[Snippet Request] Commissions withholding tax modification

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/library#89]
For new projects going forward I would be interested in seeing some example code/functions demonstrating how to modify the recorded commission amount based on the vendors country of origin and the customers country. In reality, just a basic example to get me going so I can expand on further into a full plugin.

For example the following scenarios:

1. Customer purchasing is from Sweden and vendor is based in US, in which case commission should have 20% withheld from the gross amount (original item price) (this isn't real data - just an example). The commission amount recorded should be modified based on this.

2. Ideally another example could be given showing the calculation performed on the commission amount only and not the cart item price.

**Comment by cklosowski** [comment]
We could work something up for that. Ideally after we get 3.4 out the door which will be with the new custom tables :)

**Comment by davidsherlock** [comment]
PR submitted: #104.
