### ISSUE TITLE
[Snippet Request] Calculate tax after discounts option

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/library#97]
In older EDD releases the option to calculate tax after discounts, with the ability to enable or disable it. Here is a screenshot I found on GitHub:

![8b96e6aa-28e8-11e4-9636-5b76555f05f7](https://user-images.githubusercontent.com/22668877/29996909-52dfb3b0-8fff-11e7-8b7a-dd2bd54bba16.png)

Is it possible to re-add this to the EDD (or optionally) on a per product basis?

**Comment by pippinsplugins** [comment]
We will not be providing a snippet for this nor intentionally supporting it again. Support pre and post tax calculations was easily one of the most costly features ever introduced into EDD and caused an endless stream of problems.

**Comment by davidsherlock** [comment]
Thought that might be the reason @pippinsplugins. Thanks anyway!
