### ISSUE TITLE
[Snippet Request] forcing a tax rate on a specific cart item

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/library#98]
A pretty straightforward request I "think", but wasn't sure how to approach this exactly. The logic would be as follows:

1. Customer adds various items to the cart and proceeds to checkout.

2. He/she enters his details and _IF_ one of the countries he selects has tax set, set a specific item in the cart to a forced rate (like 20%) but make sure the other items remain using the tax rate provided by the countries list.

Is this possible?

**Comment by pippinsplugins** [comment]
@davidsherlock It's definitely possible but I don't have anything on hand to illustrate how to do it.

Side note: requesting code snippets here is not exactly kosher. This is a place for code snippets we have on hand to live but it is not a place to request custom created code snippets nor guidance on how to achieve custom functionality. AKA this is not for any form of support. We applaud all of the custom work but it's just not in our capacity to provide assistance like this.

**Comment by davidsherlock** [comment]
Apologies @pippinsplugins, noted.

**Comment by pippinsplugins** [comment]
No worries, we just have to be firm on what we can and cannot provide as it easily gets out of hand if we don't :)
